### ISSUE TITLE
Adaboost方法疑问

### ISSUE THREAD

**Issue by Ritali** [SunnyMarkLiu/NaiveBayesSpamFilter#2]
DS计算部分: alpha是不是写错了？
                alpha = ps - ph
                if alpha < 0:  # 原先为spam，预测成ham
                    DS[testWordsCount != 0] = np.abs((DS[testWordsCount != 0] - np.exp(alpha)) / DS[testWordsCount != 0])
                else:  # 原先为ham，预测成spam
                    DS[testWordsCount != 0] = (DS[testWordsCount != 0] + np.exp(alpha)) / DS[testWordsCount != 0]

改成
alpha = ps - ph
                if alpha >  0:  # 原先为ham，预测成spam
                    DS[testWordsCount != 0] = np.abs((DS[testWordsCount != 0] - np.exp(alpha)) / DS[testWordsCount != 0])
                else:  # 原先为spam，预测成ham
                    DS[testWordsCount != 0] = (DS[testWordsCount != 0] + np.exp(alpha)) / DS[testWordsCount != 0]
错误率更低了。

**Comment by SunnyMarkLiu** [comment]
您好，确实是这个道理，非常感谢您指正！
`alpha = ps - ph`，如果 `alpha > 0`，表示预测的 P(S|W) > P(H|W)，实际为： P(S|W) < P(H|W)，即实际为Ham，预测成Spam了，所以Adaboost需要调整以降低P(S|W)的大小，所以需要降低 DS 的值，也就是`-np.exp(alpha)` 。
可能是我之前用的：

```
                # alpha = (ph - ps) / ps
                alpha = ps - ph
                if alpha < 0:  # 原先为spam，预测成ham
                   ...
```

后来`# alpha = (ph - ps) / ps`给注释掉了，下面的忘记修改了。
