### ISSUE TITLE
testWordsMarkedArray

### ISSUE THREAD

**Issue by zaneran** [SunnyMarkLiu/NaiveBayesSpamFilter#3]
请问testWordsMarkedArray指的是什么呢？
没有python基础看得有些吃力……不好意思哈

**Comment by zaneran** [comment]
此外还有一个问题，
计算P(Wi|S)和P(Wi|H)时，将所有词汇初始化出现的次数为1，并将分母初始化为2（或根据样本/实际调查结果调整分母的值）。
如果给了一个Spam邮件training model几千词，几乎没有什么重复的情况下，那么在将来test中，某个出现在training model的词，P(Wi|S)可能极小，接近于0，而这个词并没有出现在Health词库内，这时候给它P(Wi|H) = 0.5是不是太大了呢？请问这种情况应该怎么解决这个问题呢？
谢谢大神不吝赐教！谢谢！

**Comment by SunnyMarkLiu** [comment]
Q1：
 `testWordsCount`表示测试文本针对语料库标记该测试文本中词汇出现的次数，类似于针对语料库对测试文本“编码”的效果，参考`setOfWordsToVecTor(vocabularyList, smsWords)`函数。然后`testWordsMarkedArray`将结果转成`numpy`的`array`类型
Q2：
这种问题一般的解决方法是丰富语料库了，一般通过在线学习的方式更新语料库，同时更新`P(Wi|S)`和`P(Wi|H)`, `P(Wi|H) = 0.5` 只是为了测试，实际需要根据样本结合新增的数据进行调整。

**Comment by zaneran** [comment]
谢谢！还有一个问题，如果training样本很小，类似于就一两千词，还适合用你的这种朴素贝叶斯方法吗？还是这时候直接比对邮件关键词词频准确度会更高呢？谢谢哈～刚接触机器学习，问题比较多不好意思哈

**Comment by SunnyMarkLiu** [comment]
垃圾邮件的spamicity的词汇代表性的可能就那些，training样本很小的话可能也会有点效果，但肯定没有大数据量训练的模型准确，至于对邮件关键词匹配其实道理也是一样的，您的关键词有多少呢？也就是说关键词匹配和spamicity的词汇匹配是一样的。也就是说，我们在对测试样本词汇“编码”的过程其实就是关键词匹配了，您觉得呢？
