### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zhangyue1995** [SunnyMarkLiu/NaiveBayesSpamFilter#4]
请问这个数据集是在哪里找到的啊

**Comment by SunnyMarkLiu** [comment]
You can find it on Kaggle: [sms-spam-collection-dataset](https://www.kaggle.com/uciml/sms-spam-collection-dataset) or UCI Machine Learning Repository: [Spambase Data Set](https://archive.ics.uci.edu/ml/datasets/spambase).
